import { FontMetadata, FontCategory, FontWeight, FontStyle } from '../types';

/**
 * Curated font catalog inspired by the best of DaFont, Google Fonts, and professional typography
 * All fonts are selected for their quality, versatility, and proper licensing
 */
export const FONT_CATALOG: Record<string, FontMetadata> = {
  // Professional Sans-Serif Fonts (like Arial, Helvetica)
  inter: {
    id: 'inter',
    name: 'Inter',
    category: FontCategory.SANS_SERIF,
    weights: [
      FontWeight.THIN,
      FontWeight.EXTRA_LIGHT,
      FontWeight.LIGHT,
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.SEMI_BOLD,
      FontWeight.BOLD,
      FontWeight.EXTRA_BOLD,
      FontWeight.BLACK,
    ],
    styles: [FontStyle.NORMAL],
    fallback: ['system-ui', 'sans-serif'],
    description: 'A modern, highly legible typeface optimized for UI',
    useCases: ['UI', 'Body Text', 'Headings', 'Professional Documents'],
    pairsWith: ['playfair-display', 'merriweather', 'space-mono'],
    tags: ['modern', 'clean', 'professional', 'ui'],
    license: 'OFL',
    designer: 'Rasmus Andersson',
  },

  poppins: {
    id: 'poppins',
    name: 'Poppins',
    category: FontCategory.SANS_SERIF,
    weights: [
      FontWeight.THIN,
      FontWeight.EXTRA_LIGHT,
      FontWeight.LIGHT,
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.SEMI_BOLD,
      FontWeight.BOLD,
      FontWeight.EXTRA_BOLD,
      FontWeight.BLACK,
    ],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Geometric sans-serif with a friendly personality',
    useCases: ['Headings', 'Marketing', 'Modern Websites'],
    pairsWith: ['lato', 'merriweather', 'roboto'],
    tags: ['geometric', 'friendly', 'modern'],
    license: 'OFL',
  },

  roboto: {
    id: 'roboto',
    name: 'Roboto',
    category: FontCategory.SANS_SERIF,
    weights: [
      FontWeight.THIN,
      FontWeight.LIGHT,
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.BOLD,
      FontWeight.BLACK,
    ],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Google\'s signature typeface, mechanical yet friendly',
    useCases: ['Android Apps', 'Material Design', 'Documentation'],
    pairsWith: ['roboto-slab', 'open-sans', 'montserrat'],
    tags: ['google', 'material', 'technical'],
    license: 'Apache-2.0',
  },

  montserrat: {
    id: 'montserrat',
    name: 'Montserrat',
    category: FontCategory.SANS_SERIF,
    weights: Object.values(FontWeight),
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Urban-inspired typeface with unique character',
    useCases: ['Headings', 'Logos', 'Posters'],
    pairsWith: ['merriweather', 'lato', 'open-sans'],
    tags: ['urban', 'modern', 'bold'],
    license: 'OFL',
  },

  // Classic Serif Fonts (like Times New Roman, Georgia)
  'playfair-display': {
    id: 'playfair-display',
    name: 'Playfair Display',
    category: FontCategory.SERIF,
    weights: [
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.SEMI_BOLD,
      FontWeight.BOLD,
      FontWeight.EXTRA_BOLD,
      FontWeight.BLACK,
    ],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['Georgia', 'serif'],
    description: 'Elegant transitional serif with high contrast',
    useCases: ['Editorial', 'Luxury Brands', 'Headlines'],
    pairsWith: ['inter', 'lato', 'open-sans'],
    tags: ['elegant', 'editorial', 'classic'],
    license: 'OFL',
  },

  merriweather: {
    id: 'merriweather',
    name: 'Merriweather',
    category: FontCategory.SERIF,
    weights: [FontWeight.LIGHT, FontWeight.REGULAR, FontWeight.BOLD, FontWeight.BLACK],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['Georgia', 'serif'],
    description: 'Designed for optimal readability on screens',
    useCases: ['Blog Posts', 'E-books', 'Long-form Content'],
    pairsWith: ['montserrat', 'open-sans', 'lato'],
    tags: ['readable', 'traditional', 'screen-optimized'],
    license: 'OFL',
  },

  // Display & Creative Fonts (DaFont-style)
  'bebas-neue': {
    id: 'bebas-neue',
    name: 'Bebas Neue',
    category: FontCategory.DISPLAY,
    weights: [FontWeight.REGULAR],
    styles: [FontStyle.NORMAL],
    fallback: ['Impact', 'sans-serif'],
    description: 'Bold condensed sans-serif perfect for headlines',
    useCases: ['Posters', 'Banners', 'Sports Design'],
    pairsWith: ['roboto', 'open-sans', 'montserrat'],
    tags: ['bold', 'condensed', 'impact'],
    license: 'OFL',
  },

  oswald: {
    id: 'oswald',
    name: 'Oswald',
    category: FontCategory.DISPLAY,
    weights: [
      FontWeight.EXTRA_LIGHT,
      FontWeight.LIGHT,
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.SEMI_BOLD,
      FontWeight.BOLD,
    ],
    styles: [FontStyle.NORMAL],
    fallback: ['Arial Narrow', 'sans-serif'],
    description: 'Reworked gothic style for digital age',
    useCases: ['Headlines', 'Navigation', 'Modern Websites'],
    pairsWith: ['roboto', 'lato', 'merriweather'],
    tags: ['gothic', 'condensed', 'modern'],
    license: 'OFL',
  },

  fredoka: {
    id: 'fredoka',
    name: 'Fredoka',
    category: FontCategory.DISPLAY,
    weights: [FontWeight.LIGHT, FontWeight.REGULAR, FontWeight.MEDIUM, FontWeight.SEMI_BOLD, FontWeight.BOLD],
    styles: [FontStyle.NORMAL],
    fallback: ['Comic Sans MS', 'sans-serif'],
    description: 'Playful rounded font perfect for kids content',
    useCases: ['Children Apps', 'Games', 'Casual Brands'],
    pairsWith: ['quicksand', 'nunito', 'open-sans'],
    tags: ['playful', 'rounded', 'friendly'],
    license: 'OFL',
  },

  // Handwriting & Script Fonts
  'dancing-script': {
    id: 'dancing-script',
    name: 'Dancing Script',
    category: FontCategory.HANDWRITING,
    weights: [FontWeight.REGULAR, FontWeight.MEDIUM, FontWeight.SEMI_BOLD, FontWeight.BOLD],
    styles: [FontStyle.NORMAL],
    fallback: ['cursive'],
    description: 'Casual script with bouncing baseline',
    useCases: ['Invitations', 'Quotes', 'Personal Blogs'],
    pairsWith: ['roboto', 'lato', 'open-sans'],
    tags: ['script', 'casual', 'flowing'],
    license: 'OFL',
  },

  pacifico: {
    id: 'pacifico',
    name: 'Pacifico',
    category: FontCategory.HANDWRITING,
    weights: [FontWeight.REGULAR],
    styles: [FontStyle.NORMAL],
    fallback: ['cursive'],
    description: 'Fun brush script inspired by 1950s surf culture',
    useCases: ['Logos', 'Beach Themes', 'Casual Brands'],
    pairsWith: ['open-sans', 'roboto', 'quicksand'],
    tags: ['retro', 'surf', 'brush'],
    license: 'OFL',
  },

  caveat: {
    id: 'caveat',
    name: 'Caveat',
    category: FontCategory.HANDWRITING,
    weights: [FontWeight.REGULAR, FontWeight.MEDIUM, FontWeight.SEMI_BOLD, FontWeight.BOLD],
    styles: [FontStyle.NORMAL],
    fallback: ['cursive'],
    description: 'Natural handwriting font with marker-like appearance',
    useCases: ['Notes', 'Annotations', 'Personal Touch'],
    pairsWith: ['inter', 'roboto', 'open-sans'],
    tags: ['handwritten', 'marker', 'casual'],
    license: 'OFL',
  },

  'amatic-sc': {
    id: 'amatic-sc',
    name: 'Amatic SC',
    category: FontCategory.HANDWRITING,
    weights: [FontWeight.REGULAR, FontWeight.BOLD],
    styles: [FontStyle.NORMAL],
    fallback: ['cursive'],
    description: 'Condensed hand-drawn font with naive charm',
    useCases: ['Titles', 'Crafts', 'DIY Projects'],
    pairsWith: ['roboto', 'open-sans', 'lato'],
    tags: ['hand-drawn', 'condensed', 'naive'],
    license: 'OFL',
  },

  // Monospace Fonts (for code)
  'space-mono': {
    id: 'space-mono',
    name: 'Space Mono',
    category: FontCategory.MONOSPACE,
    weights: [FontWeight.REGULAR, FontWeight.BOLD],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['Consolas', 'monospace'],
    description: 'Monospace font for the digital age',
    useCases: ['Code', 'Terminal', 'Tech Documentation'],
    pairsWith: ['inter', 'roboto', 'open-sans'],
    tags: ['code', 'technical', 'monospace'],
    license: 'OFL',
  },

  // Additional versatile fonts
  lato: {
    id: 'lato',
    name: 'Lato',
    category: FontCategory.SANS_SERIF,
    weights: [FontWeight.THIN, FontWeight.LIGHT, FontWeight.REGULAR, FontWeight.BOLD, FontWeight.BLACK],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Humanist sans-serif with warmth',
    useCases: ['Corporate', 'Body Text', 'UI'],
    pairsWith: ['merriweather', 'playfair-display', 'roboto'],
    tags: ['humanist', 'warm', 'corporate'],
    license: 'OFL',
  },

  'open-sans': {
    id: 'open-sans',
    name: 'Open Sans',
    category: FontCategory.SANS_SERIF,
    weights: [FontWeight.LIGHT, FontWeight.REGULAR, FontWeight.MEDIUM, FontWeight.SEMI_BOLD, FontWeight.BOLD, FontWeight.EXTRA_BOLD],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Neutral and friendly humanist sans-serif',
    useCases: ['Web Content', 'Apps', 'Documents'],
    pairsWith: ['merriweather', 'playfair-display', 'roboto-slab'],
    tags: ['neutral', 'versatile', 'readable'],
    license: 'OFL',
  },

  raleway: {
    id: 'raleway',
    name: 'Raleway',
    category: FontCategory.SANS_SERIF,
    weights: Object.values(FontWeight),
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Elegant sans-serif with unique character',
    useCases: ['Fashion', 'Luxury', 'Minimalist Design'],
    pairsWith: ['merriweather', 'lato', 'roboto'],
    tags: ['elegant', 'thin', 'fashion'],
    license: 'OFL',
  },

  nunito: {
    id: 'nunito',
    name: 'Nunito',
    category: FontCategory.SANS_SERIF,
    weights: [
      FontWeight.EXTRA_LIGHT,
      FontWeight.LIGHT,
      FontWeight.REGULAR,
      FontWeight.MEDIUM,
      FontWeight.SEMI_BOLD,
      FontWeight.BOLD,
      FontWeight.EXTRA_BOLD,
      FontWeight.BLACK,
    ],
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Rounded sans-serif with soft terminals',
    useCases: ['Apps', 'Children Content', 'Friendly Brands'],
    pairsWith: ['merriweather', 'roboto-slab', 'lato'],
    tags: ['rounded', 'soft', 'approachable'],
    license: 'OFL',
  },

  quicksand: {
    id: 'quicksand',
    name: 'Quicksand',
    category: FontCategory.SANS_SERIF,
    weights: [FontWeight.LIGHT, FontWeight.REGULAR, FontWeight.MEDIUM, FontWeight.SEMI_BOLD, FontWeight.BOLD],
    styles: [FontStyle.NORMAL],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Geometric sans with rounded terminals',
    useCases: ['Display', 'Children Apps', 'Modern UI'],
    pairsWith: ['roboto', 'merriweather', 'open-sans'],
    tags: ['geometric', 'rounded', 'display'],
    license: 'OFL',
  },

  barlow: {
    id: 'barlow',
    name: 'Barlow',
    category: FontCategory.SANS_SERIF,
    weights: Object.values(FontWeight),
    styles: [FontStyle.NORMAL, FontStyle.ITALIC],
    fallback: ['system-ui', 'sans-serif'],
    description: 'Slightly rounded, low-contrast grotesk',
    useCases: ['Tech Products', 'Apps', 'Documentation'],
    pairsWith: ['playfair-display', 'merriweather', 'space-mono'],
    tags: ['grotesk', 'technical', 'california'],
    license: 'OFL',
  },
};
