import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

type ProviderType = 'postgres' | 'mongodb' | 'supabase' | 'cosmosdb' | 'sqlserver';

const commonSchema = `// This is an auto-generated schema. Do not edit this file directly.
// Run 'pnpm run generate:schemas' to regenerate.

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["filterJson"]
}
`;

const providerConfigs: Record<ProviderType, { datasource: string; generator: string }> = {
  postgres: {
    datasource: `datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_PRISMA_URL")
}`,
    generator: `generator postgresClient {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/.prisma/client-postgres"
  binaryTargets = ["native"]
}`
  },
  mongodb: {
    datasource: `datasource db {
  provider = "mongodb"
  url      = env("MONGODB_URI")
}`,
    generator: `generator mongodbClient {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/.prisma/client-mongodb"
  binaryTargets = ["native"]
}`
  },
  supabase: {
    datasource: `datasource db {
  provider = "postgresql"
  url      = env("SUPABASE_DATABASE_URL")
}`,
    generator: `generator supabaseClient {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/.prisma/client-supabase"
  binaryTargets = ["native"]
}`
  },
  cosmosdb: {
    datasource: `datasource db {
  provider = "mongodb"
  url      = env("COSMOSDB_MONGODB_URI")
}`,
    generator: `generator cosmosdbClient {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/.prisma/client-cosmosdb"
  binaryTargets = ["native"]
}`
  },
  sqlserver: {
    datasource: `datasource db {
  provider = "sqlserver"
  url      = env("SQLSERVER_URL")
}`,
    generator: `generator sqlserverClient {
  provider      = "prisma-client-js"
  output        = "../../../node_modules/.prisma/client-sqlserver"
  binaryTargets = ["native"]
}`
  }
};

const userModel = (provider: ProviderType) => `
model ${provider.charAt(0).toUpperCase() + provider.slice(1)}User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  posts     ${provider.charAt(0).toUpperCase() + provider.slice(1)}Post[]
  roles     ${provider.charAt(0).toUpperCase() + provider.slice(1)}Role[]
}`;

const postModel = (provider: ProviderType) => `
model ${provider.charAt(0).toUpperCase() + provider.slice(1)}Post {
  id        String   @id @default(cuid())
  title     String
  content   String?
  published Boolean  @default(false)
  author    ${provider.charAt(0).toUpperCase() + provider.slice(1)}User   @relation(fields: [authorId], references: [id])
  authorId  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}`;

const roleModel = (provider: ProviderType) => `
model ${provider.charAt(0).toUpperCase() + provider.slice(1)}Role {
  id          String   @id @default(cuid())
  name        String   @unique
  description String?
  users       ${provider.charAt(0).toUpperCase() + provider.slice(1)}User[]
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}`;

function generateProviderSchema(provider: ProviderType) {
  const { datasource, generator } = providerConfigs[provider];
  const schema = [
    commonSchema,
    datasource,
    '\n',
    generator,
    '\n',
    userModel(provider),
    '\n',
    postModel(provider),
    '\n',
    roleModel(provider)
  ].join('\n');

  return schema;
}

function generateAllSchemas() {
  const schemasDir = join(__dirname, '..', 'prisma', 'schemas');
  
  // Create schemas directory if it doesn't exist
  if (!existsSync(schemasDir)) {
    mkdirSync(schemasDir, { recursive: true });
  }

  // Generate schema for each provider
  (Object.keys(providerConfigs) as ProviderType[]).forEach(provider => {
    const schema = generateProviderSchema(provider);
    const outputPath = join(schemasDir, `${provider}.prisma`);
    writeFileSync(outputPath, schema);
    console.log(`Generated schema for ${provider} at ${outputPath}`);
  });

  console.log('\nAll schema files have been generated successfully!');
}

generateAllSchemas();
